name: make_docs

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: 
       - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    if: github.event.repository.fork == false
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - uses: actions/cache@v2
        with:
          key: ${{ github.ref }}
          path: .cache
      - run: pip install git+https://${{ secrets.GH_MATERIAL_MKDOCS_TOKEN }}@github.com/squidfunk/mkdocs-material-insiders.git
      - run: pip install mkdocs-jupyter
      - run: pip install pillow cairosvg # install social share card plugins
#       - run: pip install jupyter
      - run: cp *.ipynb docs/ # copy all notebooks to docs folder
      - run: cp 05_pytorch_going_modular.md docs/ # copy markdown section for 05 to docs folder
      - run: cp extras/pytorch_extra_resources.md docs/
      - run: cp extras/pytorch_cheatsheet.ipynb docs/
      - run: cp extras/pytorch_most_common_errors.ipynb docs/
      # - run: cp extras/00_pytorch_fundamentals.md docs/
      - run: mkdocs gh-deploy --force
